sonar.projectKey=MeltingNugget_cd-mcm-exercise-Neugebauer
sonar.organization=meltingnugget

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=cmd/api/main.go


sonar.sourceEncoding=UTF-8
